#pragma once

#include "ActorFlags.h"
#include "Attribute.h"
#include "../Utils/HMath.h"

class Entity;
class TextHolder;
class HashedString;
class MobEffect;
class BlockLegacy;
class Block;
class PlayerActionPacket;

class PlayerMovementProxy {
public:
	BUILD_ACCESS(this, Entity*, owningEntity, 0x10);

private:
	virtual void Destructor();

public:
	virtual void _getStateProvider(void);
	virtual void _getStateProvider2(void);
	virtual bool isRiding(void);
	virtual bool hasPassenger(void);
	virtual bool isClientside(void);
	virtual bool isCreative(void);
	virtual bool isInWater(void);
	virtual bool isInLava(void);
	virtual bool isOverScaffolding(void);
	virtual bool isSwimming(void);
	virtual bool isImmersedInWater(void);
	virtual void onHoverableBlock(void);
	virtual bool isHeadInWater(void);
	virtual bool isSwimmer(void);
	virtual bool isImmobile(void);
	virtual bool isKnockedBackOnDeath(void);
	virtual bool shouldBeImmobile(void);
	virtual bool isControlledByLocalInstance(void);
	virtual bool hasTeleported(void);
	virtual bool isWearingLeatherBoots(void);
	virtual void hasFamily(HashedString const &);
	virtual bool isWorldBuilder(void);
	virtual bool isSleeping(void);
	virtual void usesOneWayCollision(void);
	virtual bool isStuckInCollider(void);
	virtual void setStuckInCollider(bool);
	virtual bool isStuckItem(void);
	virtual int getOnewayPhysicsBlocks(void);
	virtual void wasPenetratingLastFrame(void);
	virtual void setWasPenetratingLastFrame(bool);
	virtual bool isPrimaryLocalPlayer(void);
	virtual int getSubAABBs(void);
	virtual void setSubAABBs(std::vector<AABB> const &);
	virtual int getLiquidAABB(__int64);
	virtual bool isStackable(void);
	virtual void testForEntityStacking(AABB const &, std::vector<AABB> &);
	virtual int getCollidableActorNear(void);
	virtual void setCollidableActorNear(bool);
	virtual int getWalkDist(void);
	virtual void setWalkDist(float);
	virtual bool isFlying(void);
	virtual void setIsFlying(bool);
	virtual bool isOnGround(void);
	virtual void setOnGround(bool);
	virtual bool wasOnGround(void);
	virtual void setWasOnGround(bool);
	virtual int getHealth(void);
	virtual bool getHorizontalCollision(void);
	virtual void setHorizontalCollision(bool);
	virtual bool getVerticalCollision(void);
	virtual void setVerticalCollision(bool);
	virtual bool getCollision(void);
	virtual void setCollision(bool);
	virtual float getMaxAutoStep(void);
	virtual int getHeightOffset(void);
	virtual int getSlideOffset(void);
	virtual void setSlideOffset(Vec2 const &);
	virtual void setTerrainSurfaceOffset(float);
	virtual int getBlockMovementSlowdownMultiplier(void);
	virtual void setBlockMovementSlowdownMultiplier(BlockLegacy const &, Vec3 const &);
	virtual void resetBlockMovementSlowdownMultiplier(void);
	virtual int getCurrentSwimAmount(void);
	virtual int getAttribute(Attribute const &);
	virtual void hasEffect(MobEffect const &);
	virtual int getEffect(MobEffect const &);
	virtual int getActiveEffectCount(void);
	virtual int getEntityData(void);
	virtual void setStatusFlag(ActorFlags, bool);
	virtual bool getStatusFlag(ActorFlags);
	virtual void hasCategory(int);
	virtual bool isType(int);
	virtual int getEntityTypeId(void);
	virtual int getPosition(void);
	virtual int getPosPrev(void);
	virtual void setPosDirect(Vec3 const &);
	virtual void setPosition(Vec3 const &);
	virtual int getPosDelta(void);
	virtual int getPosDeltaNonConst(void);
	virtual void setAABB(AABB const &);
	virtual AABB getAABB(void);
	virtual Vec2 getAABBDim(void);
	virtual float getAttachPos(Vec3, float);
	virtual Vec2 getRotation(void);
	virtual void setRotation(Vec2 const &);
	virtual int getPrevRotation(void);
	virtual float getFallDistance(void);
	virtual void setFallDistance(float);
	virtual bool isSneaking(void);
	virtual void setSneaking(bool);
	virtual float getHeadLookVector(float);
	virtual int getRegion(void);
	virtual int getRegionFromDimension(void);
	virtual void fetchCollisionShapes(AABB const &, float *, bool, PlayerMovementProxy *);
	virtual void fetchEntities(PlayerMovementProxy const *, AABB const &);
	virtual bool hasRegion(void);
	virtual int getVehicle(void);
	virtual bool isWASDControlled(void);
	virtual int getControllingSeat(void);
	virtual int getPassengerIndex(PlayerMovementProxy const &);
	virtual void tryAsBoat(void);
	virtual void tryAsActor(void);
	virtual void tryAsActor2(void);
	virtual void tryAsPlayer(void);
	virtual void tryAsPlayer2(void);
	virtual int getPassengerIDs(void);
	virtual int getUniqueID(void);
	virtual int getRuntimeID(void);
	virtual int getBlockPosCurrentlyStandingOn(PlayerMovementProxy *);
	virtual void shouldTriggerOnStandOn(BlockLegacy const &, Vec3i const &);
	virtual void _containsSneakCollisionShapes(AABB const &);
	virtual void move(Vec3 const &);
	virtual void moveBBs(Vec3 const &);
	virtual void checkFallDamage(float, bool);
	virtual void onBounceStarted(Vec3i const &, Block const &);
	virtual void updatePrevPosRot(void);
	virtual void sendActorMove(Vec3 const &);
	virtual void _teleportTo(Vec3 const &, bool, int, int);
	virtual void _getRawActor(void);
	virtual void _getRawActor2(void);
	virtual void _getEntityData(void);
	virtual void _setPreviousPosRot(Vec3 const &, Vec2 const &);
	virtual void _setHasTeleported(bool);
	virtual void _getAttributes(void);
	virtual void _advanceLiveFrame(__int64 const &);
	virtual __int64 *getEntity(void);
	virtual __int64 *getEntity2(void);
	virtual int getNoJumpDelay(void);
	virtual void setNoJumpDelay(int);
	virtual bool isJumping(void);
	virtual void setJumping(bool);
	virtual bool getJumpVelRedux(void);
	virtual void setJumpVelRedux(bool);
	virtual Vec3 getJumpStartPos(void);
	virtual void setJumpStartPos(Vec3 const &);
	virtual int getJumpPower(void);
	virtual int getJumpTicks(void);
	virtual void setJumpTicks(int);
	virtual void _endJump(void);
	virtual void onPlayerJump(int);
	virtual float getSpeed(void);
	virtual void setSpeed(float);
	virtual bool isSoulSpeedEnchantActive(void);
	virtual bool isSprinting(void);
	virtual void setSprinting(bool);
	virtual bool isAllowedStandSliding(void);
	virtual void discardFriction(void);
	virtual int getTilt(void);
	virtual void setTilt(float);
	virtual void _allowAscendingScaffolding(void);
	virtual void ascendBlockByJumping(void);
	virtual void descendBlockByCrouching(void);
	virtual void ascendLadder(void);
	virtual void jumpFromGround(void);
	virtual void canAscendCurrentBlockByJumping(void);
	virtual void canDescendBlockBelowByCrouching(void);
	virtual bool isGliding(void);
	virtual Vec3 getLocalMoveVelocity(void);
	virtual void setLocalMoveVelocity(Vec3 const &);
	virtual float getYRotA(void);
	virtual void setYRotA(float);
	virtual void useNewAi(void);
	virtual void newServerAiStep(void);
	virtual void updateAi(void);
	virtual void aiStep(void);
	virtual void updateAttackAnim(void);
	virtual int getNoActionTime(void);
	virtual void setNoActionTime(int);
	virtual float getYHeadRot(void);
	virtual void setYHeadRot(float);
	virtual int getSwimSpeedMultiplier(void);
	virtual void setSwimSpeedMultiplier(float);
	virtual void pushActors(void);
	virtual void updateGliding(void);
	virtual void travel(float, float, float);
	virtual void playJumpSound(void);
	virtual void emitJumpPreventedEvent(Vec3i const &);
	virtual int getWaterWalkerEnchant(void);
	virtual int getFlyingSpeed(void);
	virtual void setFlyingSpeed(float);
	virtual void applyFinalFriction(float, bool);
	virtual int getFrictionModifier(void);
	virtual void setFrictionModifier(float);
	virtual void _getActor(void);
	virtual void _setYHeadRotOld(float);
	virtual bool isSlowedByItemUse(void);
	virtual int getItemUseMovementModifier(void);
	virtual void startGliding(void);
	virtual void stopGliding(void);
	virtual bool isSpectator(void);
	virtual bool isUsingItem(void);
	virtual bool isServerAuthoritativeMovement(void);
	virtual bool isAutoJumping(void);
	virtual void setAutoJumping(bool);
	virtual bool isAutoJumpEnabled(void);
	virtual void wasAutoJumping(void);
	virtual void setWasAutoJumping(bool);
	virtual bool isAdventureSettingsAutoJump(void);
	virtual void setHasMoveInput(bool);
	virtual void hasMoveInput(void);
	virtual bool isLocalPlayer(void);
	virtual int getBob(void);
	virtual void setBob(float);
	virtual int getLastBob(void);
	virtual void setLastBob(float);
	virtual void tryGetPlayerActionComponent(void);
	virtual int getCurrentTick(void);
	virtual int getClientInstance(void);
	virtual int getClientInstance2(void);
	virtual int getMoveInputHandler(void);
	virtual int getGlidingTicks(void);
	virtual int getInputMode(void);
	virtual int getPlayMode(void);
	virtual int getVRMoveAdjustAngle(void);
	virtual int getPlayerPaddleForce(int);
	virtual void setPlayerPaddleForce(int, float);
	virtual bool isPaddling(int);
	virtual void areHandsBusy(void);
	virtual void setHandsBusy(bool);
	virtual int getAbilityBool(int);
	virtual void setAbilityBool(int, bool);
	virtual int getAbilityFloat(int);
	virtual void setAbilityFloat(int, float);
	virtual int getAbilities(void);
	virtual void updateClientPlayerInputState(void);
	virtual bool isEmoting(void);
	virtual void setEmotingStatus(bool);
	virtual void fireEventPersonaEmotePlayed(bool);
	virtual void sendPacket(PlayerActionPacket &);
	virtual void sendPacket(__int64 &);
	virtual void sendRequestAbilityPacket(int, bool);
	virtual bool isArmorFlyEnabled(void);
	virtual void setJumpRidingScale(float);
	virtual int getJumpRidingScale(void);
	virtual void registerFramewiseActionOrStop(void);
	virtual int getLoadingState(void);
	virtual void setCurrentLocalMoveVelocity(Vec2 const &);
	virtual void setLastPos(Vec3 const &);
	virtual int getLastPos(void);
	virtual void setLastDelta(Vec3 const &);
	virtual int getLastDelta(void);
	virtual void sendPlayerInput(void);
	virtual void sendInput(void);
	virtual void sendClientAuthInput(void);
	virtual void shouldSendPosition(void);
	virtual void sendPosition(void);
	virtual void checkMovementStats(Vec3 const &);
	virtual void sendPlayerMove(void);
	virtual void updateTouch(void);
	virtual void _getPlayer(void);
	virtual void _setPositionMode(int);
	virtual void _onMovePlayerPacketNormal(Vec3 const &, Vec2 const &, float);
	virtual void _resetPos(bool);
	virtual void _extractStateFromComponents(void);
	virtual void _applyStateToComponents(void);
	virtual int getControllingPlayer(void);
	virtual void setPaddleState(int, bool);
};
